<?xml version="1.0" encoding="utf-8"?><Database Name="DataBaseSchool" Class="DataClassAdminDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\DataBaseSchool.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DataBaseSchoolConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cours" Member="Cours">
    <Type Name="Cour">
      <Column Name="IdCours" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Prerequis" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NbModules" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>